apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zencastr-homework
  name: zencastr-homework
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zencastr-homework
  template:
    metadata:
      name: zencastr-homework
      labels:
        app: zencastr-homework
    spec:
      containers:
      - command:
        - npm
        - start
        image: quay.io/trown/backend:latest
        name: zencastr-homework
        ports:
        - containerPort: 8000
        resources: {}
        securityContext:
          allowPrivilegeEscalation: true
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          seLinuxOptions: {}
        workingDir: /app
      restartPolicy: Always
