apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: zencastr-homework
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: zencastr-homework
  targetCPUUtilizationPercentage: 50