kind: Service
apiVersion: v1
metadata:
  name: zencastr-homework
  labels:
    app: zencastr-homework
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    app: zencastr-homework